# Generated by Django 4.2.3 on 2023-07-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='numofpeople',
            field=models.IntegerField(),
        ),
    ]
